app.version=@project.version@
git.commit=@goldenera.git.commit@
cryptoj.version=@goldenera-cryptoj.version@
cryptoj.sha256=@goldenera.cryptoj.sha256@
release.metadata.required=@goldenera.release-metadata.required@
